name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! This was started by a commit to master"
      - name: Show the date
        run: |
          date
      - name: Show directory contents
        run: |
          ls
          