name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
#      - name: Log github context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: Log commits
#        env:
#          COMMITS: ${{ toJson(github.event.commits) }}
#        run: echo "$COMMITS"
#      - name: Log commit messages
#        env:
#          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
#        run: echo "$COMMIT_MESSAGES"
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install 
        run: npm install
      - name: eslint
        run: npm run eslint
      - name: run tests
        run: npm run test
      - name: run build
        run: npm run 
# Cypress doesn't work with this in Github actions, pass the step for now
#      - name: e2e tests
#        uses: cypress-io/github-action@v2
#        with:
#          command: npm run test:e2e
#          start: npm run start-prod
#          wait-on: http://localhost:5000
#          env: PORT=5000
      - name: Install to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sirr-pokedex"
          heroku_email: "riku.sarlin@gmail.com"
          healthcheck: "https://sirr-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        if: ${{ ((github.event_name == 'push') && (!contains(join(github.event.commits.*.message), '#skip')))}}
      - name: Another checkout for tagging to work
        uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
        if: ${{ ((github.event_name == 'push') && (!contains(join(github.event.commits.*.message), '#skip')))}}
#      - name: Slack Success Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_COLOR: ${{ job.status }}
#        if: ${{ ((job.status == 'success') && (github.event_name == 'push'))}}
#      - name: Slack Failure Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_COLOR: ${{ job.status }}
#        if: ${{ ((job.status != 'success') && (github.event_name == 'push'))}}
