name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install 
        run: npm install
      - name: eslint
        run: npm run eslint
      - name: run tests
        run: npm run test
      - name: run build
        run: npm run 
#      - name: e2e tests
#        uses: cypress-io/github-action@v2
#        with:
#          command: npm run test:e2e
#          start: npm run start-prod
#          wait-on: http://localhost:5000
#          env: PORT=5000
      - name: Install to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sirr-pokedex"
          heroku_email: "riku.sarlin@gmail.com"
          healthcheck: "https://sirr-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        if: ${{ github.event_name == 'push' }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: "0.0.4"
          DEFAULT_BUMP: "patch"
        if: ${{ github.event_name == 'push' }}
